## feature Enginering
* > 1- create total price col.
* > 2- create weekend col.
* > 3- create hour col.
* > 4- create DayOfWeek col.
* > 5- create InvoiceMonth col.
* > 6- create InvoiceYear col.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
rfm_data = pd.read_csv('rfm_data.csv')
rfm_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
rfm_data.dtypes

InvoiceNo               int64
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [4]:
rfm_data['Total_price'] = rfm_data['Quantity'] * rfm_data['UnitPrice']
rfm_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [5]:
"""
total_price :
It was created because it is important for the following:

The “Monetary” foundation in RFM
Identifying VIP clients
Profitability analysis

-------------------------------------------------------

InvoiceYear : 
Comparing performance over the years /  analyzing growth or decline.

---------------------------------------------------------

InvoiceMonth :
Discovering Seasonality / Peak Sales Months

---------------------------------------------------------

DayOfWeek:
Understanding weekly buying behavior
Do people buy more on certain days?


-------------------------------------

Hour :
Understanding peak times
Improving marketing campaigns


-----------------------------

Weekend:
Do people shop more on weekends?


"""

'\ntotal_price :\nIt was created because it is important for the following:\n\nThe “Monetary” foundation in RFM\nIdentifying VIP clients\nProfitability analysis\n\n-------------------------------------------------------\n\nInvoiceYear : \nComparing performance over the years /  analyzing growth or decline.\n\n---------------------------------------------------------\n\nInvoiceMonth :\nDiscovering Seasonality / Peak Sales Months\n\n---------------------------------------------------------\n\nDayOfWeek:\nUnderstanding weekly buying behavior\nDo people buy more on certain days?\n\n\n-------------------------------------\n\nHour :\nUnderstanding peak times\nImproving marketing campaigns\n\n\n-----------------------------\n\nWeekend:\nDo people shop more on weekends?\n\n\n'

In [6]:
rfm_data['InvoiceYear'] = rfm_data['InvoiceDate'].dt.year
rfm_data['InvoiceMonth'] = rfm_data['InvoiceDate'].dt.month
rfm_data['DayOfWeek'] = rfm_data['InvoiceDate'].dt.day_name()
rfm_data['hour'] = rfm_data['InvoiceDate'].dt.hour
rfm_data['weekend'] = (rfm_data['InvoiceDate'].dt.weekday >= 5).astype(int)
rfm_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total_price,InvoiceYear,InvoiceMonth,DayOfWeek,hour,weekend
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,Wednesday,8,0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,Wednesday,8,0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,Wednesday,8,0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,Wednesday,8,0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,Wednesday,8,0

In [7]:
rfm_data.to_csv('rfm_final_data.csv', index=False)